version: '1.0'
services:
  dg-database:
    build: ./dg-database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dg-network

  dg-backend:
    build: ./dg-backend
    ports:
      - 8000:8000
    depends_on:
      - dg-database
    networks:
      - dg-network

  dg-frontend:
    build: ./dg-frontend
    ports:
      - 3000:3000
    depends_on:
      - dg-backend
    networks:
      - dg-network

volumes:
  pgdata:

networks:
  dg-network:
