version: '1.0'
services:
  dg-database:
    build: ./dg-database
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dg_database
    ports:
      - 5432:5432
    networks:
      - dg-network

  dg-backend:
    build: ./dg-backend
    ports:
      - 8000:8000
    depends_on:
      - dg-database
    environment:
      DATABASE_URL: postgresql://postgres:postgres@dg-database:5432/dg_database
    networks:
      - dg-network

  dg-frontend:
    build: ./dg-frontend
    ports:
      - 80:80
    depends_on:
      - dg-backend
    networks:
      - dg-network

volumes:
  pgdata:

networks:
  dg-network:
