dg-frontend:
  replicas: 1
  image: cstrab/dg-frontend:7d3c0d93fc93084a15a8a870c1cc250f1856279e
  containerPort: 3000
  servicePort: 3000
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
dg-backend:
  replicas: 1
  image: cstrab/dg-backend:7d3c0d93fc93084a15a8a870c1cc250f1856279e
  containerPort: 8000
  servicePort: 8000
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
dg-database:
  replicas: 1
  image: postgres:latest
  containerPort: 5432
  servicePort: 5432
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
