dg-frontend:
  replicas: 1
  image: cstrab/dg-frontend:fe6833529ddaeeae27aa85ad3c606bb4b8f9dd3c
  containerPort: 3000
  servicePort: 3000
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
dg-backend:
  replicas: 1
  image: cstrab/dg-backend:fe6833529ddaeeae27aa85ad3c606bb4b8f9dd3c
  containerPort: 8000
  servicePort: 8000
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
dg-database:
  replicas: 1
  image: postgres:latest
  containerPort: 5432
  servicePort: 5432
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
