dg-frontend:
  replicas: 1
  image: cstrab/dg-frontend:500b8f6d6cb7508f4fe2df464123dc5a158656fd
  containerPort: 3000
  servicePort: 3000
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
dg-backend:
  replicas: 1
  image: cstrab/dg-backend:500b8f6d6cb7508f4fe2df464123dc5a158656fd
  containerPort: 8000
  servicePort: 8000
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
postgresql:
  global:
    postgresql:
      auth:
        username: "user"
        database: "dg_database"
        existingSecret: dg-app-secrets
        secretKeys:
          adminPasswordKey: db_admin_password
          userPasswordKey: db_user_password
          replicationPasswordKey: db_rep_password
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 1Gi



