name: dg-frontend
replicas: 1
image: cstrab/dg-frontend:latest
containerPort: 3000
servicePort: 3000
resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "0.5"
    memory: "256Mi"
