name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          cd dg-backend
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker buildx create --use --name mybuilder
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag cstrab/dg-backend:latest .
          docker push cstrab/dg-backend:latest

          cd ../dg-database
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker buildx create --use --name mybuilder
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag cstrab/dg-database:latest .
          docker push cstrab/dg-database:latest

          cd ../dg-frontend
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker buildx create --use --name mybuilder
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag cstrab/dg-frontend:latest .
          docker push cstrab/dg-frontend:latest
