name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push Docker image for dg-backend
        run: |
          cd dg-backend
          docker build -t ${{ secrets.REGISTRY_USERNAME }}/dg-backend:latest .
          docker push ${{ secrets.REGISTRY_USERNAME }}/dg-backend:latest

      - name: Build and push Docker image for dg-database
        run: |
          cd dg-database
          docker build -t ${{ secrets.REGISTRY_USERNAME }}/dg-database:latest .
          docker push ${{ secrets.REGISTRY_USERNAME }}/dg-database:latest

      - name: Build and push Docker image for dg-frontend
        run: |
          cd dg-frontend
          docker build -t ${{ secrets.REGISTRY_USERNAME }}/dg-frontend:latest .
          docker push ${{ secrets.REGISTRY_USERNAME }}/dg-frontend:latest
